/**
 * Builds the alligator-cracking figure used beside the sealer copy.
 *
 * Alligator (fatigue) cracking is what asphalt does when the binder has gone
 * brittle and the surface can no longer flex — it breaks into interlocking
 * plates. It is the exact failure the page is describing, so the decoration is
 * the subject rather than an abstract flourish.
 *
 * Geometry is a jittered lattice: every cell is a quad built from four shared,
 * randomly displaced corner points, so neighbouring plates always meet exactly
 * and the cracks between them read as one continuous network rather than a set
 * of outlined shapes. Some quads are split on a diagonal, because real fatigue
 * cracking is a mix of four- and three-sided plates.
 *
 * Seeded, so the output is identical on every run and the diff stays empty
 * unless the parameters actually change.
 *
 *   node scripts/generate-cracks.mjs
 */

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const OUT = join(
  dirname(fileURLToPath(import.meta.url)),
  "..",
  "src",
  "components",
  "ui",
  "cracks.generated.ts",
);

const W = 620;
const H = 760;
const COLS = 7;
const ROWS = 9;
/** Corner displacement as a fraction of cell size. Too high and plates fold. */
const JITTER = 0.34;
/** Chance a quad is split into two triangles. */
const SPLIT = 0.42;

/** Mulberry32 — small, fast, and identical across runs. */
function rng(seed) {
  return function () {
    seed |= 0;
    seed = (seed + 0x6d2b79f5) | 0;
    let t = Math.imul(seed ^ (seed >>> 15), 1 | seed);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

const rand = rng(20260812);
const between = (a, b) => a + rand() * (b - a);

// Lattice of shared corner points. Edge points are pinned on the axis they sit
// on, so the figure keeps a clean rectangular boundary to fade out from.
const cellW = W / COLS;
const cellH = H / ROWS;
const points = [];
for (let r = 0; r <= ROWS; r++) {
  const row = [];
  for (let c = 0; c <= COLS; c++) {
    const onLeft = c === 0;
    const onRight = c === COLS;
    const onTop = r === 0;
    const onBottom = r === ROWS;
    row.push({
      x: c * cellW + (onLeft || onRight ? 0 : between(-JITTER, JITTER) * cellW),
      y: r * cellH + (onTop || onBottom ? 0 : between(-JITTER, JITTER) * cellH),
    });
  }
  points.push(row);
}

const n = (v) => Math.round(v * 10) / 10;
const poly = (pts) => `M${pts.map((p) => `${n(p.x)} ${n(p.y)}`).join("L")}Z`;

/**
 * Plate fill. A narrow band of near-black greys: enough variation that the
 * plates separate from one another, not so much that it reads as a pattern.
 */
function plate() {
  const l = Math.round(between(9, 19));
  return `hsl(220 4% ${l}%)`;
}

const shapes = [];
for (let r = 0; r < ROWS; r++) {
  for (let c = 0; c < COLS; c++) {
    const tl = points[r][c];
    const tr = points[r][c + 1];
    const br = points[r + 1][c + 1];
    const bl = points[r + 1][c];

    if (rand() < SPLIT) {
      // Alternate the diagonal so the splits do not all lean the same way.
      if (rand() < 0.5) {
        shapes.push({ d: poly([tl, tr, br]), fill: plate() });
        shapes.push({ d: poly([tl, br, bl]), fill: plate() });
      } else {
        shapes.push({ d: poly([tl, tr, bl]), fill: plate() });
        shapes.push({ d: poly([tr, br, bl]), fill: plate() });
      }
    } else {
      shapes.push({ d: poly([tl, tr, br, bl]), fill: plate() });
    }
  }
}

const body = `// GENERATED by scripts/generate-cracks.mjs — do not edit by hand.
//
// Interlocking plates of an alligator-cracked surface. Every plate shares its
// edges with its neighbours, so the gaps between them form one continuous
// crack network rather than a set of separate outlines.

export const CRACK_VIEWBOX = "0 0 ${W} ${H}";

export const CRACK_PLATES: readonly { d: string; fill: string }[] = [
${shapes.map((s) => `  { d: "${s.d}", fill: "${s.fill}" },`).join("\n")}
];
`;

const previous = existsSync(OUT) ? readFileSync(OUT, "utf8") : "";
if (previous !== body) {
  writeFileSync(OUT, body);
  console.log(`cracks: wrote ${shapes.length} plates to ${OUT}`);
} else {
  console.log("cracks: unchanged");
}
