/**
 * Builds the alligator-cracking background used behind the sealer copy.
 *
 * Alligator (fatigue) cracking is what asphalt does when the binder has gone
 * brittle and the surface can no longer flex — it breaks into interlocking
 * plates. It is the exact failure the page describes, so the background is the
 * subject rather than an abstract flourish.
 *
 * Geometry is a honeycomb, because that is what fatigue cracking approximates
 * and because a hex lattice reads as scales rather than as a grid. Every
 * corner is shared by three cells, and the jitter is stored against the
 * corner's position rather than against the cell — so neighbouring cells
 * always displace a shared corner identically and the cracks stay one
 * continuous network instead of splitting into outlined shapes.
 *
 * No fills are emitted. The page background shows through the cells, so the
 * figure is only ever black and red.
 *
 * Seeded, so output is identical on every run and the diff stays empty unless
 * the parameters actually change.
 *
 *   node scripts/generate-cracks.mjs
 */

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const OUT = join(
  dirname(fileURLToPath(import.meta.url)),
  "..",
  "src",
  "components",
  "ui",
  "cracks.generated.ts",
);

/** Wide, because this spans a full-bleed section behind text. */
const W = 1800;
const H = 1300;
/**
 * Hex circumradius, in viewBox units. The figure is drawn with `slice`, so it
 * is scaled up to cover the section — keep this small and the viewBox large,
 * or the cells arrive on screen the size of dinner plates and the texture
 * reads as a graphic sitting on the page instead of a surface behind it.
 */
const R = 30;
/** Corner displacement as a fraction of R. Too high and cells self-intersect. */
const JITTER = 0.3;

/** Mulberry32 — small, fast, identical across runs. */
function rng(seed) {
  return function () {
    seed |= 0;
    seed = (seed + 0x6d2b79f5) | 0;
    let t = Math.imul(seed ^ (seed >>> 15), 1 | seed);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

const rand = rng(20260812);

/**
 * One displacement per physical corner, looked up by rounded position. Three
 * hexes meeting at a corner all read the same entry, which is what keeps the
 * lattice watertight.
 */
const corners = new Map();
function jittered(x, y) {
  const key = `${Math.round(x * 100)},${Math.round(y * 100)}`;
  let p = corners.get(key);
  if (!p) {
    p = {
      x: x + (rand() * 2 - 1) * JITTER * R,
      y: y + (rand() * 2 - 1) * JITTER * R,
    };
    corners.set(key, p);
  }
  return p;
}

// Pointy-top honeycomb. Overdrawn past every edge so the lattice reaches the
// bounds of the viewBox rather than stopping short of them.
const hStep = Math.sqrt(3) * R;
const vStep = 1.5 * R;
const cells = [];

for (let row = -2; row * vStep < H + 2 * R; row++) {
  for (let col = -2; col * hStep < W + 2 * R; col++) {
    const cx = col * hStep + (row % 2 === 0 ? 0 : hStep / 2);
    const cy = row * vStep;

    const pts = [];
    for (let i = 0; i < 6; i++) {
      const a = (Math.PI / 180) * (60 * i - 30);
      pts.push(jittered(cx + R * Math.cos(a), cy + R * Math.sin(a)));
    }
    cells.push(pts);
  }
}

const n = (v) => Math.round(v * 10) / 10;
const paths = cells.map((pts) => `M${pts.map((p) => `${n(p.x)} ${n(p.y)}`).join("L")}Z`);

const body = `// GENERATED by scripts/generate-cracks.mjs — do not edit by hand.
//
// A jittered honeycomb whose cells share every corner, so the gaps between
// them form one continuous crack network. Stroked only — the cells carry no
// fill, so whatever is behind the figure shows through them.

export const CRACK_VIEWBOX = "0 0 ${W} ${H}";

export const CRACK_CELLS: readonly string[] = [
${paths.map((d) => `  "${d}",`).join("\n")}
];
`;

const previous = existsSync(OUT) ? readFileSync(OUT, "utf8") : "";
if (previous !== body) {
  writeFileSync(OUT, body);
  console.log(`cracks: wrote ${paths.length} cells (${corners.size} shared corners) to ${OUT}`);
} else {
  console.log("cracks: unchanged");
}
