// GENERATED by scripts/resolve-surfaces.mjs — do not edit by hand.
//
// Regenerated on every build. To change which image a surface uses, add or
// remove the file in public/photos and rebuild; see public/photos/README.md.

export const SURFACE_SRC = {
  hero: "/textures/asphalt-hero.jpg", // photo missing — generated texture
  oxidized: "/photos/dried-asphalt.jpg",
  crack: "/photos/crack-sealing.jpg",
  pothole: "/photos/pothole.jpg",
  lot: "/photos/line-striping.jpg",
  driveway: "/photos/sealcoating.jpg",
  sealerEdge: "/photos/sealer-edge.jpg",
  crackedLot: "/photos/lot-before.jpg",
} as const;

export type SurfaceName = keyof typeof SURFACE_SRC;
